on: [ push ]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: check files
        run: ls
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash
