on: 
  pull_request:
    branches: [master, dev]
name: ci_python
jobs:
  run_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: install pipenv
        run: |
          ls
          python -m pip install --upgrade pip
          pip install pipenv
      - name: install packages
        run: |
          pipenv install
      - name: test pipenv
        run: |
          pytest
          


